export const MINUTE_MILLISECONDS = 1000 * 60;
export const DAY_MILLISECONDS = MINUTE_MILLISECONDS * 60 * 24;

export const SALT_ROUNDS = 10;

export const FOREIGN_KEY_VIOLATION_ERRCODE = 23503;
export const UNIQUE_VIOLATION_ERRCODE = 23505;

export const FIRST_VALID_YEAR = 2020;

export const MIN_PETITION_VOTES = 100;
export const MIN_RESOLUTION_VOTES = 50;

export const RESOLUTION_WINDOW_MILLISECONDS = DAY_MILLISECONDS * 30;
export const SCHOOL_CHANGE_MILLISECONDS = DAY_MILLISECONDS * 15;

export const PAGE_SIZE = 12;
