export enum Length
{
    EMAIL = 320,
    MIN_RESOLUTION_TEXT = 1,
    MAX_RESOLUTION_TEXT = 500,
    MIN_PETITION_TITLE = 1,
    MAX_PETITION_TITLE = 300,
    MIN_PETITION_DESC = 1,
    MAX_PETITION_DESC = 500,
    MIN_COMMENT = 1,
    MAX_COMMENT = 300,
    MAX_SEARCH = 100,
    MIN_PASSWORD = 8,
    MAX_PASSWORD = 15,
    HASH_LENGTH = 60
}